micronaut:
  application:
    name: micronaut-demo-r2dbc

flyway:
  enabled: true
  datasources:
    default:
      enabled: true

#datasources:
#  default:
#    url: jdbc:h2:file:./target/foobar
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#
#r2dbc:
#  datasources:
#    default:
#      url: r2dbc:h2:file:////Users/aalmiray/dev/github/demos/micronaut-demo-r2dbc/target/foobar
#      username: sa
#      password: ''
#      schema-generate: CREATE_DROP
#      dialect: H2

datasources:
  default:
    schema-generate: CREATE_DROP
    dialect: ORACLE
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    driverClassName: oracle.jdbc.OracleDriver
    username: System
    password: Admin01

r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: ORACLE
      url: r2dbc:oracle://localhost:1521/XEPDB1
      username: System
      password: Admin01
