micronaut:
  application:
    name: micronaut-demo-r2dbc

flyway:
  enabled: true
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true

datasources:
  default:
    schema-generate: CREATE_DROP
    dialect: ORACLE
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    driverClassName: oracle.jdbc.OracleDriver
    username: System
    password: Admin01

r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: ORACLE
      url: r2dbc:oracle://localhost:1521/XEPDB1
      username: System
      password: Admin01
